name: PHP Composer Build and Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

#    - name: Cache Composer dependencies
#      uses: actions/cache@v3
#      with:
#        path: vendor
#        key: composer-${{ hashFiles('composer.lock') }}
#        restore-keys: |
#          composer-

#    - name: Validate composer.json and composer.lock
#      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

#    - name: Cache build artifacts
#      uses: actions/cache@v3
#      with:
#        path: builds
#        key: build-${{ github.sha }}
#        restore-keys: |
#          build-

    - name: Build application
      run: php awkirin app:build awkirin

    - name: Create Latest Release
      if: github.ref == 'refs/heads/main'
      run: |
        gh release delete latest -y --cleanup-tag 2>/dev/null || true
        gh release create latest \
          --title "Latest Build ($(date +'%Y-%m-%d %H:%M'))" \
          --notes "Автоматическая сборка из main branch" \
          --latest \
          builds/awkirin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
